# Generated by Django 5.0.6 on 2024-05-31 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.TextField(verbose_name="street")),
                ("city", models.TextField(verbose_name="city")),
                ("state", models.TextField(verbose_name="state")),
                ("number", models.IntegerField(verbose_name="number")),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "db_table": "api_data_address",
            },
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                ("phone", models.CharField(max_length=15, verbose_name="phone number")),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buty_center.address",
                        verbose_name="address",
                    ),
                ),
            ],
            options={
                "verbose_name": "center",
                "verbose_name_plural": "centers",
                "db_table": "api_data_center",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CenterService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buty_center.center",
                        verbose_name="center",
                    ),
                ),
            ],
            options={
                "verbose_name": "center_service",
                "verbose_name_plural": "center_services",
                "db_table": "api_data_center_service",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("mark", models.FloatField(verbose_name="mark")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buty_center.center",
                        verbose_name="center",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "api_data_comment",
                "ordering": ["mark"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                ("category", models.TextField(verbose_name="category")),
                (
                    "centers",
                    models.ManyToManyField(
                        through="buty_center.CenterService",
                        to="buty_center.center",
                        verbose_name="centers",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "db_table": "api_data_service",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="centerservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="buty_center.service",
                verbose_name="service",
            ),
        ),
    ]
