name: Run tests

on:
  push:
    branches:
      - main  # Здесь указывается ветка, на которой запускается workflow
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379  # Пример сервиса Redis, если он нужен для вашего проекта
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose services
        run: |
          cd hw4  # Переход в каталог с docker-compose.yml
          docker-compose up -d --build
        env:
          DOCKER_BUILDKIT: 1  # Включение BuildKit для ускорения сборки

      - name: Run tests
        run: |
          cd hw4  # Переход в каталог с docker-compose.yml
          docker-compose run --rm app python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: project.settings.test
          PYTHONPATH: .
          # Дополнительные переменные окружения, если нужны

      - name: Shutdown Docker Compose services
        run: |
          cd hw4  # Переход в каталог с docker-compose.yml
          docker-compose down
