name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml run --rm app python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: project.settings.test
          PYTHONPATH: .

      - name: Shutdown Docker Compose services
        run: docker-compose -f docker-compose.yml down
