name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hw4/requirements.txt

    - name: Run Django tests
      run: |
        ./run_tests.sh tests.test_api

    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports

    - name: Send coverage data to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
